PeMMO
## Level Requirements

# Mining (How many blocks should the player have to break to level up)
mining.lvl1: 128

mining.lvl2: 500

mining.lvl3: 1000

mining.lvl4: 2500

mining.lvl5: 5000

# Tree cutting (How many trees should the player have to break to level up)
treecutting.lvl1: 128

treecutting.lvl2: 500

treecutting.lvl3: 1000

treecutting.lvl4: 2500

treecutting.lvl5: 5000

# Combat (How many entities should the player have to kill to level up)
combat.lvl1: 128

combat.lvl2: 500

combat.lvl3: 1000

combat.lvl4: 2500

combat.lvl5: 5000
